/**
 * Seeds iso_countries and iso_us_subdivisions tables with ISO 3166-1 / 3166-2:US data.
 * Run with: npx tsx scripts/seed-lookup-tables.ts
 */
import { createClient } from "@supabase/supabase-js"
import * as dotenv from "dotenv"

dotenv.config({ path: ".env.local" })

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_KEY!
)

// ISO 3166-1 countries
const COUNTRIES: { alpha2: string; alpha3: string; numeric: string; name: string }[] = [
  { alpha2: "AF", alpha3: "AFG", numeric: "004", name: "Afghanistan" },
  { alpha2: "AL", alpha3: "ALB", numeric: "008", name: "Albania" },
  { alpha2: "DZ", alpha3: "DZA", numeric: "012", name: "Algeria" },
  { alpha2: "AD", alpha3: "AND", numeric: "020", name: "Andorra" },
  { alpha2: "AO", alpha3: "AGO", numeric: "024", name: "Angola" },
  { alpha2: "AG", alpha3: "ATG", numeric: "028", name: "Antigua and Barbuda" },
  { alpha2: "AR", alpha3: "ARG", numeric: "032", name: "Argentina" },
  { alpha2: "AM", alpha3: "ARM", numeric: "051", name: "Armenia" },
  { alpha2: "AU", alpha3: "AUS", numeric: "036", name: "Australia" },
  { alpha2: "AT", alpha3: "AUT", numeric: "040", name: "Austria" },
  { alpha2: "AZ", alpha3: "AZE", numeric: "031", name: "Azerbaijan" },
  { alpha2: "BS", alpha3: "BHS", numeric: "044", name: "Bahamas" },
  { alpha2: "BH", alpha3: "BHR", numeric: "048", name: "Bahrain" },
  { alpha2: "BD", alpha3: "BGD", numeric: "050", name: "Bangladesh" },
  { alpha2: "BB", alpha3: "BRB", numeric: "052", name: "Barbados" },
  { alpha2: "BY", alpha3: "BLR", numeric: "112", name: "Belarus" },
  { alpha2: "BE", alpha3: "BEL", numeric: "056", name: "Belgium" },
  { alpha2: "BZ", alpha3: "BLZ", numeric: "084", name: "Belize" },
  { alpha2: "BJ", alpha3: "BEN", numeric: "204", name: "Benin" },
  { alpha2: "BT", alpha3: "BTN", numeric: "064", name: "Bhutan" },
  { alpha2: "BO", alpha3: "BOL", numeric: "068", name: "Bolivia" },
  { alpha2: "BA", alpha3: "BIH", numeric: "070", name: "Bosnia and Herzegovina" },
  { alpha2: "BW", alpha3: "BWA", numeric: "072", name: "Botswana" },
  { alpha2: "BR", alpha3: "BRA", numeric: "076", name: "Brazil" },
  { alpha2: "BN", alpha3: "BRN", numeric: "096", name: "Brunei" },
  { alpha2: "BG", alpha3: "BGR", numeric: "100", name: "Bulgaria" },
  { alpha2: "BF", alpha3: "BFA", numeric: "854", name: "Burkina Faso" },
  { alpha2: "BI", alpha3: "BDI", numeric: "108", name: "Burundi" },
  { alpha2: "CV", alpha3: "CPV", numeric: "132", name: "Cabo Verde" },
  { alpha2: "KH", alpha3: "KHM", numeric: "116", name: "Cambodia" },
  { alpha2: "CM", alpha3: "CMR", numeric: "120", name: "Cameroon" },
  { alpha2: "CA", alpha3: "CAN", numeric: "124", name: "Canada" },
  { alpha2: "CF", alpha3: "CAF", numeric: "140", name: "Central African Republic" },
  { alpha2: "TD", alpha3: "TCD", numeric: "148", name: "Chad" },
  { alpha2: "CL", alpha3: "CHL", numeric: "152", name: "Chile" },
  { alpha2: "CN", alpha3: "CHN", numeric: "156", name: "China" },
  { alpha2: "CO", alpha3: "COL", numeric: "170", name: "Colombia" },
  { alpha2: "KM", alpha3: "COM", numeric: "174", name: "Comoros" },
  { alpha2: "CD", alpha3: "COD", numeric: "180", name: "Congo, Democratic Republic" },
  { alpha2: "CG", alpha3: "COG", numeric: "178", name: "Congo, Republic" },
  { alpha2: "CR", alpha3: "CRI", numeric: "188", name: "Costa Rica" },
  { alpha2: "CI", alpha3: "CIV", numeric: "384", name: "Côte d'Ivoire" },
  { alpha2: "HR", alpha3: "HRV", numeric: "191", name: "Croatia" },
  { alpha2: "CU", alpha3: "CUB", numeric: "192", name: "Cuba" },
  { alpha2: "CY", alpha3: "CYP", numeric: "196", name: "Cyprus" },
  { alpha2: "CZ", alpha3: "CZE", numeric: "203", name: "Czechia" },
  { alpha2: "DK", alpha3: "DNK", numeric: "208", name: "Denmark" },
  { alpha2: "DJ", alpha3: "DJI", numeric: "262", name: "Djibouti" },
  { alpha2: "DM", alpha3: "DMA", numeric: "212", name: "Dominica" },
  { alpha2: "DO", alpha3: "DOM", numeric: "214", name: "Dominican Republic" },
  { alpha2: "EC", alpha3: "ECU", numeric: "218", name: "Ecuador" },
  { alpha2: "EG", alpha3: "EGY", numeric: "818", name: "Egypt" },
  { alpha2: "SV", alpha3: "SLV", numeric: "222", name: "El Salvador" },
  { alpha2: "GQ", alpha3: "GNQ", numeric: "226", name: "Equatorial Guinea" },
  { alpha2: "ER", alpha3: "ERI", numeric: "232", name: "Eritrea" },
  { alpha2: "EE", alpha3: "EST", numeric: "233", name: "Estonia" },
  { alpha2: "SZ", alpha3: "SWZ", numeric: "748", name: "Eswatini" },
  { alpha2: "ET", alpha3: "ETH", numeric: "231", name: "Ethiopia" },
  { alpha2: "FJ", alpha3: "FJI", numeric: "242", name: "Fiji" },
  { alpha2: "FI", alpha3: "FIN", numeric: "246", name: "Finland" },
  { alpha2: "FR", alpha3: "FRA", numeric: "250", name: "France" },
  { alpha2: "GA", alpha3: "GAB", numeric: "266", name: "Gabon" },
  { alpha2: "GM", alpha3: "GMB", numeric: "270", name: "Gambia" },
  { alpha2: "GE", alpha3: "GEO", numeric: "268", name: "Georgia" },
  { alpha2: "DE", alpha3: "DEU", numeric: "276", name: "Germany" },
  { alpha2: "GH", alpha3: "GHA", numeric: "288", name: "Ghana" },
  { alpha2: "GR", alpha3: "GRC", numeric: "300", name: "Greece" },
  { alpha2: "GD", alpha3: "GRD", numeric: "308", name: "Grenada" },
  { alpha2: "GT", alpha3: "GTM", numeric: "320", name: "Guatemala" },
  { alpha2: "GN", alpha3: "GIN", numeric: "324", name: "Guinea" },
  { alpha2: "GW", alpha3: "GNB", numeric: "624", name: "Guinea-Bissau" },
  { alpha2: "GY", alpha3: "GUY", numeric: "328", name: "Guyana" },
  { alpha2: "HT", alpha3: "HTI", numeric: "332", name: "Haiti" },
  { alpha2: "HN", alpha3: "HND", numeric: "340", name: "Honduras" },
  { alpha2: "HU", alpha3: "HUN", numeric: "348", name: "Hungary" },
  { alpha2: "IS", alpha3: "ISL", numeric: "352", name: "Iceland" },
  { alpha2: "IN", alpha3: "IND", numeric: "356", name: "India" },
  { alpha2: "ID", alpha3: "IDN", numeric: "360", name: "Indonesia" },
  { alpha2: "IR", alpha3: "IRN", numeric: "364", name: "Iran" },
  { alpha2: "IQ", alpha3: "IRQ", numeric: "368", name: "Iraq" },
  { alpha2: "IE", alpha3: "IRL", numeric: "372", name: "Ireland" },
  { alpha2: "IL", alpha3: "ISR", numeric: "376", name: "Israel" },
  { alpha2: "IT", alpha3: "ITA", numeric: "380", name: "Italy" },
  { alpha2: "JM", alpha3: "JAM", numeric: "388", name: "Jamaica" },
  { alpha2: "JP", alpha3: "JPN", numeric: "392", name: "Japan" },
  { alpha2: "JO", alpha3: "JOR", numeric: "400", name: "Jordan" },
  { alpha2: "KZ", alpha3: "KAZ", numeric: "398", name: "Kazakhstan" },
  { alpha2: "KE", alpha3: "KEN", numeric: "404", name: "Kenya" },
  { alpha2: "KI", alpha3: "KIR", numeric: "296", name: "Kiribati" },
  { alpha2: "KW", alpha3: "KWT", numeric: "414", name: "Kuwait" },
  { alpha2: "KG", alpha3: "KGZ", numeric: "417", name: "Kyrgyzstan" },
  { alpha2: "LA", alpha3: "LAO", numeric: "418", name: "Laos" },
  { alpha2: "LV", alpha3: "LVA", numeric: "428", name: "Latvia" },
  { alpha2: "LB", alpha3: "LBN", numeric: "422", name: "Lebanon" },
  { alpha2: "LS", alpha3: "LSO", numeric: "426", name: "Lesotho" },
  { alpha2: "LR", alpha3: "LBR", numeric: "430", name: "Liberia" },
  { alpha2: "LY", alpha3: "LBY", numeric: "434", name: "Libya" },
  { alpha2: "LI", alpha3: "LIE", numeric: "438", name: "Liechtenstein" },
  { alpha2: "LT", alpha3: "LTU", numeric: "440", name: "Lithuania" },
  { alpha2: "LU", alpha3: "LUX", numeric: "442", name: "Luxembourg" },
  { alpha2: "MG", alpha3: "MDG", numeric: "450", name: "Madagascar" },
  { alpha2: "MW", alpha3: "MWI", numeric: "454", name: "Malawi" },
  { alpha2: "MY", alpha3: "MYS", numeric: "458", name: "Malaysia" },
  { alpha2: "MV", alpha3: "MDV", numeric: "462", name: "Maldives" },
  { alpha2: "ML", alpha3: "MLI", numeric: "466", name: "Mali" },
  { alpha2: "MT", alpha3: "MLT", numeric: "470", name: "Malta" },
  { alpha2: "MH", alpha3: "MHL", numeric: "584", name: "Marshall Islands" },
  { alpha2: "MR", alpha3: "MRT", numeric: "478", name: "Mauritania" },
  { alpha2: "MU", alpha3: "MUS", numeric: "480", name: "Mauritius" },
  { alpha2: "MX", alpha3: "MEX", numeric: "484", name: "Mexico" },
  { alpha2: "FM", alpha3: "FSM", numeric: "583", name: "Micronesia" },
  { alpha2: "MD", alpha3: "MDA", numeric: "498", name: "Moldova" },
  { alpha2: "MC", alpha3: "MCO", numeric: "492", name: "Monaco" },
  { alpha2: "MN", alpha3: "MNG", numeric: "496", name: "Mongolia" },
  { alpha2: "ME", alpha3: "MNE", numeric: "499", name: "Montenegro" },
  { alpha2: "MA", alpha3: "MAR", numeric: "504", name: "Morocco" },
  { alpha2: "MZ", alpha3: "MOZ", numeric: "508", name: "Mozambique" },
  { alpha2: "MM", alpha3: "MMR", numeric: "104", name: "Myanmar" },
  { alpha2: "NA", alpha3: "NAM", numeric: "516", name: "Namibia" },
  { alpha2: "NR", alpha3: "NRU", numeric: "520", name: "Nauru" },
  { alpha2: "NP", alpha3: "NPL", numeric: "524", name: "Nepal" },
  { alpha2: "NL", alpha3: "NLD", numeric: "528", name: "Netherlands" },
  { alpha2: "NZ", alpha3: "NZL", numeric: "554", name: "New Zealand" },
  { alpha2: "NI", alpha3: "NIC", numeric: "558", name: "Nicaragua" },
  { alpha2: "NE", alpha3: "NER", numeric: "562", name: "Niger" },
  { alpha2: "NG", alpha3: "NGA", numeric: "566", name: "Nigeria" },
  { alpha2: "KP", alpha3: "PRK", numeric: "408", name: "North Korea" },
  { alpha2: "MK", alpha3: "MKD", numeric: "807", name: "North Macedonia" },
  { alpha2: "NO", alpha3: "NOR", numeric: "578", name: "Norway" },
  { alpha2: "OM", alpha3: "OMN", numeric: "512", name: "Oman" },
  { alpha2: "PK", alpha3: "PAK", numeric: "586", name: "Pakistan" },
  { alpha2: "PW", alpha3: "PLW", numeric: "585", name: "Palau" },
  { alpha2: "PA", alpha3: "PAN", numeric: "591", name: "Panama" },
  { alpha2: "PG", alpha3: "PNG", numeric: "598", name: "Papua New Guinea" },
  { alpha2: "PY", alpha3: "PRY", numeric: "600", name: "Paraguay" },
  { alpha2: "PE", alpha3: "PER", numeric: "604", name: "Peru" },
  { alpha2: "PH", alpha3: "PHL", numeric: "608", name: "Philippines" },
  { alpha2: "PL", alpha3: "POL", numeric: "616", name: "Poland" },
  { alpha2: "PT", alpha3: "PRT", numeric: "620", name: "Portugal" },
  { alpha2: "QA", alpha3: "QAT", numeric: "634", name: "Qatar" },
  { alpha2: "RO", alpha3: "ROU", numeric: "642", name: "Romania" },
  { alpha2: "RU", alpha3: "RUS", numeric: "643", name: "Russia" },
  { alpha2: "RW", alpha3: "RWA", numeric: "646", name: "Rwanda" },
  { alpha2: "KN", alpha3: "KNA", numeric: "659", name: "Saint Kitts and Nevis" },
  { alpha2: "LC", alpha3: "LCA", numeric: "662", name: "Saint Lucia" },
  { alpha2: "VC", alpha3: "VCT", numeric: "670", name: "Saint Vincent and the Grenadines" },
  { alpha2: "WS", alpha3: "WSM", numeric: "882", name: "Samoa" },
  { alpha2: "SM", alpha3: "SMR", numeric: "674", name: "San Marino" },
  { alpha2: "ST", alpha3: "STP", numeric: "678", name: "Sao Tome and Principe" },
  { alpha2: "SA", alpha3: "SAU", numeric: "682", name: "Saudi Arabia" },
  { alpha2: "SN", alpha3: "SEN", numeric: "686", name: "Senegal" },
  { alpha2: "RS", alpha3: "SRB", numeric: "688", name: "Serbia" },
  { alpha2: "SC", alpha3: "SYC", numeric: "690", name: "Seychelles" },
  { alpha2: "SL", alpha3: "SLE", numeric: "694", name: "Sierra Leone" },
  { alpha2: "SG", alpha3: "SGP", numeric: "702", name: "Singapore" },
  { alpha2: "SK", alpha3: "SVK", numeric: "703", name: "Slovakia" },
  { alpha2: "SI", alpha3: "SVN", numeric: "705", name: "Slovenia" },
  { alpha2: "SB", alpha3: "SLB", numeric: "090", name: "Solomon Islands" },
  { alpha2: "SO", alpha3: "SOM", numeric: "706", name: "Somalia" },
  { alpha2: "ZA", alpha3: "ZAF", numeric: "710", name: "South Africa" },
  { alpha2: "SS", alpha3: "SSD", numeric: "728", name: "South Sudan" },
  { alpha2: "KR", alpha3: "KOR", numeric: "410", name: "South Korea" },
  { alpha2: "ES", alpha3: "ESP", numeric: "724", name: "Spain" },
  { alpha2: "LK", alpha3: "LKA", numeric: "144", name: "Sri Lanka" },
  { alpha2: "SD", alpha3: "SDN", numeric: "729", name: "Sudan" },
  { alpha2: "SR", alpha3: "SUR", numeric: "740", name: "Suriname" },
  { alpha2: "SE", alpha3: "SWE", numeric: "752", name: "Sweden" },
  { alpha2: "CH", alpha3: "CHE", numeric: "756", name: "Switzerland" },
  { alpha2: "SY", alpha3: "SYR", numeric: "760", name: "Syria" },
  { alpha2: "TW", alpha3: "TWN", numeric: "158", name: "Taiwan" },
  { alpha2: "TJ", alpha3: "TJK", numeric: "762", name: "Tajikistan" },
  { alpha2: "TZ", alpha3: "TZA", numeric: "834", name: "Tanzania" },
  { alpha2: "TH", alpha3: "THA", numeric: "764", name: "Thailand" },
  { alpha2: "TL", alpha3: "TLS", numeric: "626", name: "Timor-Leste" },
  { alpha2: "TG", alpha3: "TGO", numeric: "768", name: "Togo" },
  { alpha2: "TO", alpha3: "TON", numeric: "776", name: "Tonga" },
  { alpha2: "TT", alpha3: "TTO", numeric: "780", name: "Trinidad and Tobago" },
  { alpha2: "TN", alpha3: "TUN", numeric: "788", name: "Tunisia" },
  { alpha2: "TR", alpha3: "TUR", numeric: "792", name: "Türkiye" },
  { alpha2: "TM", alpha3: "TKM", numeric: "795", name: "Turkmenistan" },
  { alpha2: "TV", alpha3: "TUV", numeric: "798", name: "Tuvalu" },
  { alpha2: "UG", alpha3: "UGA", numeric: "800", name: "Uganda" },
  { alpha2: "UA", alpha3: "UKR", numeric: "804", name: "Ukraine" },
  { alpha2: "AE", alpha3: "ARE", numeric: "784", name: "United Arab Emirates" },
  { alpha2: "GB", alpha3: "GBR", numeric: "826", name: "United Kingdom" },
  { alpha2: "US", alpha3: "USA", numeric: "840", name: "United States" },
  { alpha2: "UY", alpha3: "URY", numeric: "858", name: "Uruguay" },
  { alpha2: "UZ", alpha3: "UZB", numeric: "860", name: "Uzbekistan" },
  { alpha2: "VU", alpha3: "VUT", numeric: "548", name: "Vanuatu" },
  { alpha2: "VE", alpha3: "VEN", numeric: "862", name: "Venezuela" },
  { alpha2: "VN", alpha3: "VNM", numeric: "704", name: "Vietnam" },
  { alpha2: "YE", alpha3: "YEM", numeric: "887", name: "Yemen" },
  { alpha2: "ZM", alpha3: "ZMB", numeric: "894", name: "Zambia" },
  { alpha2: "ZW", alpha3: "ZWE", numeric: "716", name: "Zimbabwe" },
]

// ISO 3166-2:US subdivisions (50 states + DC)
const US_SUBDIVISIONS: { code: string; name: string; type: string }[] = [
  { code: "AL", name: "Alabama", type: "State" },
  { code: "AK", name: "Alaska", type: "State" },
  { code: "AZ", name: "Arizona", type: "State" },
  { code: "AR", name: "Arkansas", type: "State" },
  { code: "CA", name: "California", type: "State" },
  { code: "CO", name: "Colorado", type: "State" },
  { code: "CT", name: "Connecticut", type: "State" },
  { code: "DE", name: "Delaware", type: "State" },
  { code: "FL", name: "Florida", type: "State" },
  { code: "GA", name: "Georgia", type: "State" },
  { code: "HI", name: "Hawaii", type: "State" },
  { code: "ID", name: "Idaho", type: "State" },
  { code: "IL", name: "Illinois", type: "State" },
  { code: "IN", name: "Indiana", type: "State" },
  { code: "IA", name: "Iowa", type: "State" },
  { code: "KS", name: "Kansas", type: "State" },
  { code: "KY", name: "Kentucky", type: "State" },
  { code: "LA", name: "Louisiana", type: "State" },
  { code: "ME", name: "Maine", type: "State" },
  { code: "MD", name: "Maryland", type: "State" },
  { code: "MA", name: "Massachusetts", type: "State" },
  { code: "MI", name: "Michigan", type: "State" },
  { code: "MN", name: "Minnesota", type: "State" },
  { code: "MS", name: "Mississippi", type: "State" },
  { code: "MO", name: "Missouri", type: "State" },
  { code: "MT", name: "Montana", type: "State" },
  { code: "NE", name: "Nebraska", type: "State" },
  { code: "NV", name: "Nevada", type: "State" },
  { code: "NH", name: "New Hampshire", type: "State" },
  { code: "NJ", name: "New Jersey", type: "State" },
  { code: "NM", name: "New Mexico", type: "State" },
  { code: "NY", name: "New York", type: "State" },
  { code: "NC", name: "North Carolina", type: "State" },
  { code: "ND", name: "North Dakota", type: "State" },
  { code: "OH", name: "Ohio", type: "State" },
  { code: "OK", name: "Oklahoma", type: "State" },
  { code: "OR", name: "Oregon", type: "State" },
  { code: "PA", name: "Pennsylvania", type: "State" },
  { code: "RI", name: "Rhode Island", type: "State" },
  { code: "SC", name: "South Carolina", type: "State" },
  { code: "SD", name: "South Dakota", type: "State" },
  { code: "TN", name: "Tennessee", type: "State" },
  { code: "TX", name: "Texas", type: "State" },
  { code: "UT", name: "Utah", type: "State" },
  { code: "VT", name: "Vermont", type: "State" },
  { code: "VA", name: "Virginia", type: "State" },
  { code: "WA", name: "Washington", type: "State" },
  { code: "WV", name: "West Virginia", type: "State" },
  { code: "WI", name: "Wisconsin", type: "State" },
  { code: "WY", name: "Wyoming", type: "State" },
  { code: "DC", name: "District of Columbia", type: "District" },
  { code: "PR", name: "Puerto Rico", type: "Territory" },
  { code: "GU", name: "Guam", type: "Territory" },
  { code: "VI", name: "U.S. Virgin Islands", type: "Territory" },
  { code: "AS", name: "American Samoa", type: "Territory" },
  { code: "MP", name: "Northern Mariana Islands", type: "Territory" },
]

async function seed() {
  console.log("Seeding iso_countries…")
  const { error: ce } = await supabase
    .from("iso_countries")
    .upsert(COUNTRIES, { onConflict: "alpha2" })
  if (ce) {
    console.error("iso_countries error:", ce.message)
  } else {
    console.log(`✓ ${COUNTRIES.length} countries inserted/updated`)
  }

  console.log("Seeding iso_us_subdivisions…")
  const { error: se } = await supabase
    .from("iso_us_subdivisions")
    .upsert(US_SUBDIVISIONS, { onConflict: "code" })
  if (se) {
    console.error("iso_us_subdivisions error:", se.message)
  } else {
    console.log(`✓ ${US_SUBDIVISIONS.length} US subdivisions inserted/updated`)
  }
}

seed().catch(console.error)
